<?php
			return array(
			'URL_MODEL' => 2,//URL伪静态模式
			'water' => '0',
			'waterPosition' => '9',
			'waterImage' => '/Public/img/df81.png',
			'transparency' => '100',
			'waterText' => 'df81.com',
			'waterfont' => 'STXINGKA.TTF',
			'watercolor' => '#ff0000',
			'watersize' => '60',
			'thumb' => '1',
			'thumbwidth' => '680',
			'thumbheight' => '680',
			'imageMaxSize' => '200',
			'fileMaxSize' => '5',
			'separator' => '-',
			'istitle' => '1',
			'authgroup' => '1',
			'authrule' => '1',
			'language' => '1',
			'module' => '1',
			'parametersetting' => '1',
			'navigation' => '1',
			'advertisement' => '1',
			'comment' => '1',
			'seosetting' => '',
			'area' => '1',
			'copyright' => '1',
			'chat' => '1',
			'thumbnail' => '0',
			'databackup' => '1',
			
            );